DROP DATABASE IF EXISTS resturant_db;
CREATE DATABASE resturant_db;

DROP DATABASE IF EXISTS recipe_db;
CREATE DATABASE recipe_db;

DROP DATABASE IF EXISTS user_db;
CREATE DATABASE user_db;

DROP DATABASE IF EXISTS favorites_db;
CREATE DATABASE favorites_db;